#ifndef __org_libreoffice_librelaw_librelaw_idl__
#define __org_libreoffice_librelaw_librelaw_idl__

#include <com/sun/star/task/XJobExecutor.idl>
module org { module libreoffice { module librelaw {

	service LibreLaw : com::sun::star::task::XJobExecutor {

	};

 }; }; };
#endif
