#!/bin/sh
UNOPKG_PATH="$(which unopkg)"
LIBRECUST_MACRO_PATH="/tmp/librecust/LibreCustLib*"
SETTINGS_LOADER_PATH="/tmp/librecust/settings_*"
AUTOTEXT_WIZARD_PATH="/tmp/librecust/Autotext*"
LAW_TOOLBAR_PATH="/tmp/librecust/LawAddon*"
MENUBAR_PATH="/tmp/librecust/menubar.xml"
TOOLBAR_SINGLE_PATH="/tmp/librecust/singlemode.xml"
TOOLBAR_TEXTOBJ_PATH="/tmp/librecust/textobjectbar.xml"
PAGE_NUMBERING_PATH="/tmp/librecust/PageNumbering*"
SPELL_CHECK_PATH="/tmp/librecust/orthos*"
USER_HOME_PATH="$(eval echo "~$different_user")"


USER_NAME="$(eval echo $(basename $USER_HOME_PATH))"
USER_PROFILE_PATH="$USER_HOME_PATH/.config/libreoffice/4/user/config"
MENUBAR_DIR="$USER_PROFILE_PATH/soffice.cfg/modules/swriter/menubar" #INSTALLED MENUBAR
TOOLBAR_DIR="$USER_PROFILE_PATH/soffice.cfg/modules/swriter/toolbar"
INSTALLATION_TIMESTAMP="$(timestamp)"

set -e

case "$1" in
    purge)
        rm -rf /var/cache/librecust
            eval sudo -u $USER_NAME $UNOPKG_PATH remove com.addon.pagenumbering || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove com.addon.autotextaddon || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove org.openoffice.legacy.LibreCustLib.oxt || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove org.libreoffice.settings_loader || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove org.kasenides.el-GR-en-US-dictionary || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove com.addon.lawaddon || true
            LAST_MENUBAR="$(ls -1 | sort -r 2>&1 | head -n 1)"
            cp "$MENUBAR_DIR/$LAST_MENUBAR" "$MENUBAR_DIR/menubar.xml" || true

            LAST_TOOLBAR_DIR="$(ls -1 | sort -r 2>&1 | head -n 1)"
            cp "$TOOLBAR_DIR/$LAST_TOOLBAR_DIR/* $TOOLBAR_DIR/" || true

        if [ -e /usr/share/debconf/confmodule ]
        then
                # Source debconf library and purge db
                . /usr/share/debconf/confmodule
                db_purge
        fi
        ;;
    remove|upgrade)
        rm -rf /var/cache/librecust
            eval sudo -u $USER_NAME $UNOPKG_PATH remove com.addon.pagenumbering || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove com.addon.lawaddon || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove com.addon.autotextaddon || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove org.openoffice.legacy.LibreCustLib.oxt || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove org.libreoffice.settings_loader || true
            eval sudo -u $USER_NAME $UNOPKG_PATH remove org.kasenides.el-GR-en-US-dictionary || true
            LAST_MENUBAR="$(ls -1 | sort -r 2>&1 | head -n 1)"
            cp "$MENUBAR_DIR/$LAST_MENUBAR" "$MENUBAR_DIR/menubar.xml" || true

            LAST_TOOLBAR_DIR="$(ls -1 | sort -r 2>&1 | head -n 1)"
            cp "$TOOLBAR_DIR/$LAST_TOOLBAR_DIR/* $TOOLBAR_DIR/" || true

        ;;
    failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0